#!/bin/bash -x

read -p "Enter the number of flip you want : " num

HHcount=0
TTcount=0
HTcount=0
THcount=0

for (( i=0;i<$num;i++ ))
do
	flip=$(($((RANDOM%10))%4))
	if [ $flip -eq 0 ]
	then
		echo "HH"
		HHcount=$(($HHcount+1))
	elif [ $flip -eq 1 ]
	then
		echo "TT"
		TTcount=$(($TTcount+1))
	elif [ $flip -eq 2 ]
	then
		HTcount=$(($HTcount+1))
		echo "HTcount"
	else
		echo "TH"
		THcount=$(($THcount+1))
	fi
done

echo "number of HH count is : " $HHcount
echo "number of TT count is : " $TTcount
echo "number of HT count is : " $HTcount
echo "number of TH count is : " $THcount

percentageOfHH=$(($(($HHcount*100))/$num))
percentageOfTT=$(($(($TTcount*100))/$num))
percentageofHT=$(($(($HTcount*100))/$num))
percentageOfTH=$(($(($THcount*100))/$num))


echo "HH=$percentageOfHH%"
echo "TT=$percentageOfTT%"
echo "HT=$percentageOfHT%"
echo "TH=$percentageOfTH%"

dict[doublet]="{HH=$HHcount:%=$percentageOfHH TT=$TTcount:%=$percentageOfTT HT=$HTcount:%=$percentageOFHT TH=$THcount:%=$percentageOFTH}"
echo ${dict[@]}
